/** @type {import('tailwindcss').Config} */
// Design tokens mirror ui/intelligent_service_core/DESIGN.md (Enterprise Blue / Inter).
module.exports = {
  content: [
    "./app/**/*.{tsx,jsx,ts,html,js}",
    "./src/**/*.{tsx,jsx,ts,html,js}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#00618b",
        "on-secondary-fixed-variant": "#38485d",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed-variant": "#0040a2",
        "on-tertiary-fixed-variant": "#004c6e",
        "on-secondary-fixed": "#0b1c30",
        "on-surface": "#191c1e",
        secondary: "#505f76",
        "surface-bright": "#f7f9fb",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container": "#eceef0",
        "outline-variant": "#c3c6d6",
        "surface-container-high": "#e6e8ea",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed": "#d3e4fe",
        "on-tertiary-container": "#a7d9ff",
        "primary-fixed": "#dae2ff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        background: "#f7f9fb",
        "surface-variant": "#e0e3e5",
        primary: "#003d9b",
        surface: "#f7f9fb",
        error: "#ba1a1a",
        "inverse-primary": "#b2c5ff",
        "secondary-container": "#d0e1fb",
        "primary-container": "#0052cc",
        "on-secondary-container": "#54647a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed-dim": "#b7c8e1",
        "tertiary-fixed-dim": "#89ceff",
        "surface-tint": "#0c56d0",
        "on-primary-fixed": "#001848",
        tertiary: "#004869",
        outline: "#737685",
        "tertiary-fixed": "#c9e6ff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434654",
        "on-tertiary-fixed": "#001e2f",
        "on-primary-container": "#c4d2ff",
        "surface-container-highest": "#e0e3e5",
        "inverse-surface": "#2d3133",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "display-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        gutter: "24px",
        base: "4px",
        margin: "32px",
      },
      screens: {
        phone: { min: "320px", max: "767px" },
        pad: { min: "768px", max: "1200px" },
        pc: { min: "1200px" },
      },
    },
  },
  plugins: [],
};
